### ISSUE TITLE
Incorrect behaviour of default output directory on first run

### ISSUE THREAD

**Issue by chrisjbillington** [labscript-suite/runmanager#71]
Upon first running runmanager after install, when there is no labscript file loaded from a saved config file, it incorrectly has the warning about a non-default output directory displayed:

![image](https://user-images.githubusercontent.com/1044087/80822755-60eb7900-8ba9-11ea-9daa-85f04435c602.png)

Upon subsequently choosing a labscript file, it doesn't set the output directory correctly:

![image](https://user-images.githubusercontent.com/1044087/80822806-7b255700-8ba9-11ea-8b9e-9b4630a495ea.png)

The "set default output directory" button is even greyed out. To workaround, one must choose an output directory manually, then the "set default output directory" button is enabled and can be used to restore things to sanity.

**Comment by philipstarkey** [comment]
So this is due to the fix for #69. I think possibly that fix went about it in the wrong way. I think #69 only happened when the labscript file was set when loading in a config (either at startup or manually) because selecting a new labscript file via the GUI called `check_output_folder_update()` which should always have updated `self.previous_default_output_folder` so the explicit addition of updating that variable in `on_labscript_file_text_changed()` is unnecessary.

Possibly the fix should be to remove `check_output_folder_update()` from `on_select_labscript_file_clicked()` and modify `on_labscript_file_text_changed()` to call `check_output_folder_update()`.
